### ISSUE TITLE
support for OCaml 4.02.0?

### ISSUE THREAD

**Issue by vogler** [ocaml-batteries-team/batteries-included#572]
Everything works fine with 4.01.0, but

```
opam switch 4.02.0+trunk
opam install batteries
```

fails with

```
===== ERROR while installing batteries.2.2.0 =====
# opam-version 1.1.1
# os           linux
# command      make all
# path         /home/voglerr/.opam/4.02.0+trunk/build/batteries.2.2.0
# compiler     4.02.0+trunk
# exit-code    2
# env-file     /home/voglerr/.opam/4.02.0+trunk/build/batteries.2.2.0/batteries-25696-5f1023.env
# stdout-file  /home/voglerr/.opam/4.02.0+trunk/build/batteries.2.2.0/batteries-25696-5f1023.out
# stderr-file  /home/voglerr/.opam/4.02.0+trunk/build/batteries.2.2.0/batteries-25696-5f1023.err
### stdout ###
# ...[truncated]
# File "src/batPervasives.ml", line 166, characters 17-30:
# Warning 3: deprecated feature: Obj.final_tag
# ocamlfind ocamlc -c -g -annot -package bigarray,num,str -I src -I testsuite -I qtest -I benchsuite -I build -o src/batPrintexc.cmo src/batPrintexc.ml
# ocamlfind ocamlc -c -g -annot -package bigarray,num,str -I src -I testsuite -I qtest -I benchsuite -I build -o src/batPrintf.cmo src/batPrintf.ml
# + ocamlfind ocamlc -c -g -annot -package bigarray,num,str -I src -I testsuite -I qtest -I benchsuite -I build -o src/batPrintf.cmo src/batPrintf.ml
# File "src/batPrintf.ml", line 141, characters 4-40:
# Warning 3: deprecated feature: String.set
# File "src/batPrintf.ml", line 524, characters 24-45:
# Error: Unbound module Printf.CamlinternalPr
# Command exited with code 2.
### stderr ###
# File "setup.ml", line 213, characters 8-26:
# Warning 3: deprecated feature: String.set
# make: *** [all] Error 10
```
