### ISSUE TITLE
should we make a minor release soon?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#731]
If we need to finish some things before the release, please say so.

**Comment by gasche** [comment]
One thing that would be nice is an automated test somewhere that checks that the *installation* of Batteries went smoothly, by compiling some Batteries-dependent piece of code using the installed (and not the locally-built) Batteries version. Having this would have caught the issues I had to fight against during the last Batteries release, with linking errors related to the addition of new files only showing up after installation.

**Comment by UnixJunkie** [comment]
I do this test by hand.
Maybe I can come up with a script.

**Comment by gasche** [comment]
You must do this test by hand, but my point was that a script would be more robust. Whatever you do, please note it in the "release howto" file.

**Comment by UnixJunkie** [comment]
I just made a proposal for the test thingy: https://github.com/ocaml-batteries-team/batteries-included/pull/732.
Feel free to edit it if you think it is not harsh enough.

**Comment by gasche** [comment]
I think it would be nice if you were in charge of the release process this time -- and it is fitting given that you did most of the decision-making work for the recent changes. I would of course be happy to provide advice/guidance when necessary.

Whenever you have time, you could follow the steps of [howto/release.md](https://github.com/ocaml-batteries-team/batteries-included/blob/master/howto/release.md) until the "Performing the actual release" phase. You can send this as a pull-request for review.

We need to update the release process in relation to ocamlforge: now that the forge is deprecated we should just release on the Github project page. The `release.md` list also lacks a discussion of how to update the local `opam` file and how to prepare the opam-repository request. I will work on this right now, and send this as a pull-request for review.

**Comment by UnixJunkie** [comment]
tests on a 64bits machine are OK

**Comment by UnixJunkie** [comment]
./scripts/test_install.sh too

**Comment by UnixJunkie** [comment]
@since NEXT_RELEASE have been updated. I also polished the changelog with some missing bits.

**Comment by UnixJunkie** [comment]
make release works

**Comment by UnixJunkie** [comment]
what is the oldest compiler version we support? I'd like to run a make test in there.
3.12.1?

**Comment by UnixJunkie** [comment]
@c-cube  this part in src/batInnerShuffle.ml doesn't compile with 3.12.1:
Error: Unbound module Gen

    (*$Q
      Q.(array_of_size Gen.(2--15) small_int) (fun a -> \
        let a' = Array.copy a in \
        array_shuffle a'; \
        (Array.to_list a' |> List.sort Pervasives.compare) = \
         (Array.to_list a |> List.sort Pervasives.compare))
    *)

**Comment by c-cube** [comment]
it's because qtest is only available for OCaml >= 4.00.0 (it uses GADTs internally).

**Comment by UnixJunkie** [comment]
make test is OK in a 32bits VM

**Comment by UnixJunkie** [comment]
@c-cube other tests are OK, I guess we can ignore this one

**Comment by c-cube** [comment]
Sorry :-/
I admit that I don't maintain anything with compatibility with 3.12 as a goal now

**Comment by UnixJunkie** [comment]
I think I'm done with everything said in the release howto.
If other maintainers are OK, I can push a new tag for this version.

**Comment by UnixJunkie** [comment]
cf. https://github.com/ocaml-batteries-team/batteries-included/pull/747

**Comment by UnixJunkie** [comment]
CI tests in progress here https://github.com/ocaml/opam-repository/pull/8942

**Comment by UnixJunkie** [comment]
I propose this as the release e-mail:
## Batteries-2.6.0

Batteries Included is a community-maintained standard library
extension, with a focus on performance, stability and compatibility.
Bug reports, pull requests and user feedback are warmly welcome, see the
project page at
  https://github.com/ocaml-batteries-team/batteries-included/

The library's API documentation can be found at:
  http://ocaml-batteries-team.github.io/batteries-included/hdoc2/

Batteries 2.6.0 is a minor release, compatible with OCaml 4.04.0.

As usual, Batteries 2.6.0 is compatible with older OCaml releases as well
(until OCaml-3.12.1), and provides back-ported
versions of most standard library functions made available recently.

Soon, after an 'opam update' your will be able to do an
'opam upgrade batteries' an enjoy this new release.

Many thanks to the contributors for this release:
 Florian Angeletti
 Francois Berenger
 Michael Färber
 Oscar Gauthier
 Ifaz Kabir
 Johannes Kloos
 Gabriel Scherer
 Thibault Suzanne

## Detailed Changelog

## v2.6.0 (minor release)

- added BatList.favg and faster BatList.fsum
  #746
  (Gabriel Scherer, Francois Berenger)

- install .cmt and .cmti files
  #740
  (Francois Berenger, Gabriel Scherer)

- BatMap: added find_default
  #730
  (Francois Berenger)

- added scripts/test_install.sh
  #743
  (Francois Berenger)

- BatHashtbl: added {to|of}_list, bindings
  #728
  (Francois Berenger, Thibault Suzanne)

- added {BatList|BatArray}.shuffle
  #702, #707
  (Francois Berenger, Gabriel Scherer)

- Clarification and improvements to the documentation
  #682, #685, #693
  (Florian Angeletti, Johannes Kloos, Michael Färber)

- make `LazyList.split_at` lazy:
  `split_at : int -> 'a t -> 'a t * 'a t`
  would previously eagerly force the prefix of the list
  and only be lazy in its second returned value.
  #694
  (Michael Färber, Gabriel Scherer, Thibault Suzanne)

- Add `List.{map2i,iter2i}`
  #696
  (Thibault Suzanne)

- Added `Result.{map,map_both}`
  #705
  (Ifaz Kabir)

- Add {BatSet,BatMap}.{Int,Int32,Int64,Nativeint,Float,Char,String} as
  common instantions of the respective `Make` functor.
  #709, #712
  (Thibault Suzanne, Francois Berenger)

- BatString: add `chop : ?l:int -> ?r:int -> string -> string`
  #714, #716
  (Gabriel Scherer, request by Francois Berenger)

- BatSet: make `to_array` allocate the resulting array at first
  instead of using Dynarray (faster, uses less memory).
  #724
  (Thibault Suzanne)

- BatList: add `fold_left_map:
  ('a -> 'b -> 'a * 'c) -> 'a -> 'b list -> 'a * 'c list`
  #734
  (Thibault Suzanne, review by Gabriel Scherer, request by Oscar Gauthier)

- add ``BatList.frange :
  float -> [< `To | `Downto ] -> float -> int -> float list``
  ``frange 0. `To 1. 3`` is `[0.; 0.5; 1.]`.
  #745
  (Francois Berenger)

Happy hacking!
The Batteries maintainers.

**Comment by gasche** [comment]
This looks perfect -- I wouldn't have written something better. Thanks a lot!
Feel free to send it whenever the release is available on the opam-repository.
