### PR TITLE
Fix build on OCaml < 4.05

### PR DESCRIPTION
**Pull request by murmour**
This fixes a build issue introduced in #856.

### CODE REVIEW

**Comment by murmour** [comment]
(also, this is one of those cases where explicit exception handling looks nice)

**Comment by gasche** [comment]
Good catch, thanks!

**Comment by thizanne** [comment]
Another way to fix it would have been to move `cut_on_char` after the conditional redefinition of `index_from_opt` for `< 4.05`. No strong opinion here though, and thanks for the catch (also, sorry for not thinking to test before 4.05).
