### ISSUE TITLE
ocaml-batteries fails to build with camomile 0.8.1

### ISSUE THREAD

**Issue by dlight** [ocaml-batteries-team/batteries-included#96]
the latest git version fails to build with camomile 0.8.1. 0.7.3 works fine. details on this IRC log:

<dark> thelema, you here? File "src/batCamomile.ml", line 11, characters 13-50: Error: Unbound module CamomileLibrary.CamomileDefaultConfig
<dark> while doing ocamlfind ocamlc -c -package camomile,num,str -I src -I libs -I testsuite -I libs/estring -I build/optcomp -I src/syntax/pa_comprehension -I src/syntax/pa_strings -o src/batCamomile.cmo src/batCamomile.ml
<dark> I had batteries installed from git (and it worked fine for a lot of time), but I am rebuilding it because my build fail at link time with:
<dark> Error: Files /usr/lib/ocaml/batteries/batteries.cma(BatCamomile) 00043 / 00052 and /usr/lib/ocaml/camomile/camomile.cma(CamomileLibrary) make inconsistent assumptions over interface CamomileLibrary
<dark> I think I updated camomile or something. :(
<dark> I have camomile 0.8.1 installed, and I think I had 0.7.3 before (when everything worked fine)
<dark> I installed from git because of a small fix you put there (I think it was related to documentation), but I'm otherwise using 1.2.2
<dark> but when I tried to rebuild batteries, it cloned the current master, not the master I was using..
<dark> yeah, that was the problem. I think I will open something on the issue tracker..

[ that was the problem = camomile 0.8.1 ]
