### PR TITLE
Make it compile on OCaml 5

### PR DESCRIPTION
**Pull request by sim642**
Related to issue #1081.

I've brutally massacred our boy to make it compile (and pass tests) on OCaml 5:

1. Use stdlib-shims and campl-streams for some backwards compatibility. They have a `ocaml >= 4.02.3` lower bound instead of Batteries' current `ocaml >= 4.00.0`, but that should be reasonable enough if a new major version is to be supported.
2. Naively replace `Pervasives` with `Stdlib`. Of course this changes Batteries' interface, but thanks to stdlib-shims that should work for the entire version range. This replacement makes up most of the diff.
3. Delete bunch of deprecated functions that OCaml 5 removed. I suppose some more reasonable backwards compatibility could be provided for OCaml 4, but if there's going to be a new major Batteries version, then it might be easier to just bite the bullet and make lots of breaking changes at once.
4. Disable a few tests that otherwise fail, probably due to changes to `Random`.

**As-is, this definitely should not be merged.** But it provides a tentative overview of the changes that would be necessary, but probably is broken on OCaml 4 right now.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Thanks a lot for the trial.
I will have a look at your thing.
Of course, the PR is huge, so reviewing will take some time.

**Comment by UnixJunkie** [comment]
Maybe I'll create an ocaml5 branch and try to merge your work in there, little by little.

**Comment by Sudha247** [comment]
Thanks for your work @sim642! I'd imagine this would take time for reviewing as @UnixJunkie mentioned above, owing to the size of its changes. Meanwhile, if this branch works with `5.0.0~alpha1` switch, feel free to make a patch to add it to https://github.com/kit-ty-kate/opam-alpha-repository/tree/master/packages

**Comment by UnixJunkie** [comment]
If the PR was broken in to several, each dealing with a distinct aspect, this would significantly accelerate the review process.
For example: one PR fixes all compilation errors with the same error message.

**Comment by UnixJunkie** [comment]
I am starting to look at this right now.
Not sure how long it will take me.
I will do several partial merge I guess (if I can group things into related concerns).

**Comment by UnixJunkie** [comment]
the num library can still be installed; even with ocaml-5:
```bash
opam pin add num https://github.com/ocaml/num.git
```

**Comment by sim642** [comment]
> I am starting to look at this right now.
> Not sure how long it will take me.
> I will do several partial merge I guess (if I can group things into related concerns).

Thanks! Looking at this commit by commit is probably the easiest anyway because most of the diff is the `Pervasives`→`Stdlib` rename, which makes other changes hard to notice.

If I remember correctly, the commits are in an order to fix one build problem after another, as they come up. The dirtiest commit is https://github.com/ocaml-batteries-team/batteries-included/pull/1085/commits/1b0c17734f3ec966baf353d5e51744555b948a23 because there I just deleted now-removed deprecated functions, but didn't add all the newer non-deprecated alternatives that they have in `Stdlib`, which should eventually be done.

**Comment by UnixJunkie** [comment]
superseded by https://github.com/ocaml-batteries-team/batteries-included/pull/1086

**Comment by UnixJunkie** [comment]
@sim642 I think I just used your proposed changes for BatFormat.
You are welcome to review the PR I just mentioned.
The diff should be way smaller compared to what you initially proposed.
